apiVersion: batch/v1
kind: Job
metadata:
  name: cicd-bookstore-db-deployer
  labels:
    app: cicd-bookstore-db-deployer
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      labels:
        app: cicd-bookstore-db-deployer
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      containers:
        - image: prajwalmanohar/cicd-bookstore-db-deployer:latest
          imagePullPolicy: Always
          name: cap-db-deployer
          envFrom:
          - secretRef:
              name: orders-vcap-services
