apiVersion: v1
kind: Secret
metadata:
  name: orders-html5-deployer-secret
  labels:
    app: orders-html5-deployer
stringData:
  EXIT_PROCESS_AFTER_UPLOAD: "true"
  PORT: "5000"
  SAP_CLOUD_SERVICE: "cap.orders.kyma.service"
  SUBACCOUNT_LEVEL_DESTINATION: "true"
  BACKEND_DESTINATIONS: "[{
    \"Name\":\"cap-bookstore-kyma-srv\",
    \"Description\":\"cap orders kyma application\",
    \"Type\":\"HTTP\",
    \"ProxyType\":\"Internet\",
    \"tokenServiceURLType\": \"Dedicated\",
    \"Authentication\":\"OAuth2UserTokenExchange\",
    \"HTML5.DynamicDestination\": true,
    \"clientId\": \"sb-cap-bookstore-kyma!t208399\",
    \"clientSecret\":\"d0f9101f-20d1-430e-b5c2-67ee460ee93f$uGMm-ShdtFyCt2CZ-2J5p0cOOZ88XTeYuvAzKhdL8gI=\",
    \"tokenServiceURL\": \"https://541b28d7trial.authentication.us10.hana.ondemand.com/oauth/token\",
    \"URL\":\"https://cap-orders-service.c-33eff16.kyma.ondemand.com\"}]"